### ISSUE TITLE
In the tutorial for this, the code section is missing an import assets

### ISSUE THREAD

**Issue by rishavs** [Vladar4/ng2bounce#1]
Link: https://vladar4.github.io/nimgame2/tut101_bounce.html#loadingassets

The code section for data.nim should be

```
import
  nimgame2 / [
    ...
    <<assets>>,
    texturegraphic,
    ...
  ]

...

var
  ...
  gfxData*:Assets[TextureGraphic]


proc loadData*() =
  ...

  gfxData = newAssets[TextureGraphic](
    "data/gfx",
    proc(file: string): TextureGraphic = newTextureGraphic(file))


proc freeData*() =
  ...
  for graphic in gfxData.values:
    graphic.free()
```

For a completely new user this can cause some confusion.

**Comment by Vladar4** [comment]
This issue really belongs to Nimgame2 repo.

Fixed in devel branch: https://github.com/Vladar4/nimgame2/commit/f34539c449bedc3cf3f02eea34e87651a4fbeb2a

Will be included in the upcoming 0.7 release.
