### ISSUE TITLE
Missing line on Tutorial

### ISSUE THREAD

**Issue by kidandcat** [Vladar4/ng2bounce#2]
First thank you so much!
Your tutorials are awesome, thanks for spend your time!

In the bounce tutorial, you are missing the initialization of the ball's radius:

https://github.com/Vladar4/ng2bounce/blob/032f9603fa8fb96066dc154eea4e08ee72e27336/src/ball.nim#L36

This causes collisions to not work because they rely on the ball radius.

**Comment by Vladar4** [comment]
Thanks!
I assume you mean it's missing from the tutorial text on the site?

**Comment by kidandcat** [comment]
Exactly, in the tutorial's fragment of code

**Comment by Vladar4** [comment]
Fixed in https://github.com/Vladar4/nimgame2/commit/e56d2d5c0f960f24905a91e3327db3ba79ba7174

P.S.: Please, for the future, post site typos into the nimgame2 repo, since the site is located there.
